import type { Channel } from "@/types/channel"
import type { Video } from "@/types/video"
import type { Comment } from "@/types/comment"
import type { Category } from "@/types/category"

export const channels: Channel[] = [
  {
    id: "ch-1",
    name: "TechVault",
    handle: "@techvault",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=techvault",
    bannerUrl: "https://picsum.photos/seed/banner1/1280/720",
    description: "Deep dives into software engineering, system design, and the latest tech trends.",
    subscribers: 2_400_000,
    videoCount: 340,
    joinedAt: "2019-03-14T00:00:00Z",
  },
  {
    id: "ch-2",
    name: "CreativePixels",
    handle: "@creativepixels",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=creativepixels",
    bannerUrl: "https://picsum.photos/seed/banner2/1280/720",
    description: "UI/UX design, motion graphics, and creative coding tutorials.",
    subscribers: 1_850_000,
    videoCount: 520,
    joinedAt: "2020-07-22T00:00:00Z",
  },
  {
    id: "ch-3",
    name: "CodeJourney",
    handle: "@codejourney",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=codejourney",
    bannerUrl: "https://picsum.photos/seed/banner3/1280/720",
    description: "Learn full-stack development from scratch. Real projects, real skills.",
    subscribers: 3_100_000,
    videoCount: 280,
    joinedAt: "2018-11-05T00:00:00Z",
  },
  {
    id: "ch-4",
    name: "GameSphere",
    handle: "@gamesphere",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=gamesphere",
    bannerUrl: "https://picsum.photos/seed/banner4/1280/720",
    description: "Game reviews, walkthroughs, and gaming culture.",
    subscribers: 5_600_000,
    videoCount: 890,
    joinedAt: "2017-06-19T00:00:00Z",
  },
]

export const categories: Category[] = [
  { id: "all", name: "All" },
  { id: "music", name: "Music" },
  { id: "gaming", name: "Gaming" },
  { id: "news", name: "News" },
  { id: "sports", name: "Sports" },
  { id: "education", name: "Education" },
  { id: "technology", name: "Technology" },
  { id: "entertainment", name: "Entertainment" },
]

const now = Date.now()
const day = 86_400_000

export const videos: Video[] = [
  {
    id: "vid-1",
    title: "Build a Production-Grade YouTube Clone with Next.js 16",
    description:
      "In this comprehensive tutorial, we build a full-featured YouTube clone using Next.js 16, TypeScript, and modern React patterns. Learn about server components, streaming, and more.",
    thumbnailUrl: "https://picsum.photos/seed/vid1/320/180",
    duration: "42:15",
    views: 1_234_567,
    createdAt: new Date(now - 2 * day).toISOString(),
    channelId: "ch-1",
    categoryId: "technology",
    tags: ["nextjs", "react", "typescript", "tutorial"],
    likes: 45_000,
    commentsCount: 1_200,
  },
  {
    id: "vid-2",
    title: "The Art of Color Theory in UI Design",
    description:
      "Understanding color theory is essential for every designer. In this video, we explore how to create harmonious color palettes for your next project.",
    thumbnailUrl: "https://picsum.photos/seed/vid2/320/180",
    duration: "18:42",
    views: 856_234,
    createdAt: new Date(now - 5 * day).toISOString(),
    channelId: "ch-2",
    categoryId: "education",
    tags: ["design", "color-theory", "ui", "tutorial"],
    likes: 28_000,
    commentsCount: 850,
  },
  {
    id: "vid-3",
    title: "I Tried 10 Hidden VS Code Extensions So You Don't Have To",
    description:
      "From productivity boosters to hidden gems, here are 10 VS Code extensions that will transform your development workflow.",
    thumbnailUrl: "https://picsum.photos/seed/vid3/320/180",
    duration: "12:08",
    views: 2_100_000,
    createdAt: new Date(now - 1 * day).toISOString(),
    channelId: "ch-3",
    categoryId: "technology",
    tags: ["vscode", "extensions", "productivity", "tools"],
    likes: 67_000,
    commentsCount: 2_300,
  },
  {
    id: "vid-4",
    title: "Elden Ring: Every Secret Boss You Missed",
    description:
      "We explore every hidden boss in Elden Ring that most players completely missed. Spoilers ahead!",
    thumbnailUrl: "https://picsum.photos/seed/vid4/320/180",
    duration: "25:30",
    views: 4_500_000,
    createdAt: new Date(now - 12 * day).toISOString(),
    channelId: "ch-4",
    categoryId: "gaming",
    tags: ["elden-ring", "gaming", "bosses", "secrets"],
    likes: 180_000,
    commentsCount: 5_600,
  },
  {
    id: "vid-5",
    title: "React Server Components Explained in 15 Minutes",
    description:
      "RSC is the future of React. Learn what server components are, how they work, and when to use them with practical examples.",
    thumbnailUrl: "https://picsum.photos/seed/vid5/320/180",
    duration: "15:22",
    views: 678_900,
    createdAt: new Date(now - 3 * day).toISOString(),
    channelId: "ch-1",
    categoryId: "technology",
    tags: ["react", "server-components", "nextjs", "frontend"],
    likes: 22_000,
    commentsCount: 640,
  },
  {
    id: "vid-6",
    title: "How I Built a Design System in 7 Days",
    description:
      "A behind-the-scenes look at creating a scalable design system from scratch. Tokens, components, documentation, and more.",
    thumbnailUrl: "https://picsum.photos/seed/vid6/320/180",
    duration: "32:50",
    views: 1_100_000,
    createdAt: new Date(now - 8 * day).toISOString(),
    channelId: "ch-2",
    categoryId: "education",
    tags: ["design-system", "ui", "components", "figma"],
    likes: 39_000,
    commentsCount: 1_100,
  },
  {
    id: "vid-7",
    title: "TypeScript 5.7: Everything New",
    description:
      "A deep dive into TypeScript 5.7 features including better type narrowing, const type parameters, and performance improvements.",
    thumbnailUrl: "https://picsum.photos/seed/vid7/320/180",
    duration: "20:45",
    views: 345_678,
    createdAt: new Date(now - 1 * day).toISOString(),
    channelId: "ch-3",
    categoryId: "technology",
    tags: ["typescript", "javascript", "programming", "update"],
    likes: 12_000,
    commentsCount: 340,
  },
  {
    id: "vid-8",
    title: "Top 10 Most Anticipated Games of 2026",
    description:
      "From AAA blockbusters to indie darlings, here are the games we're most excited about this year.",
    thumbnailUrl: "https://picsum.photos/seed/vid8/320/180",
    duration: "14:18",
    views: 3_200_000,
    createdAt: new Date(now - 4 * day).toISOString(),
    channelId: "ch-4",
    categoryId: "gaming",
    tags: ["gaming", "upcoming", "2026", "preview"],
    likes: 95_000,
    commentsCount: 3_800,
  },
  {
    id: "vid-9",
    title: "CSS Grid vs Flexbox: When to Use What",
    description:
      "Stop guessing which layout method to use. This practical guide explains the strengths of each with real-world examples.",
    thumbnailUrl: "https://picsum.photos/seed/vid9/320/180",
    duration: "22:10",
    views: 910_000,
    createdAt: new Date(now - 6 * day).toISOString(),
    channelId: "ch-1",
    categoryId: "education",
    tags: ["css", "grid", "flexbox", "web-dev"],
    likes: 31_000,
    commentsCount: 920,
  },
  {
    id: "vid-10",
    title: "The Dark Side of Microservices",
    description:
      "Microservices aren't always the answer. We examine real-world cases where monoliths would have been a better choice.",
    thumbnailUrl: "https://picsum.photos/seed/vid10/320/180",
    duration: "28:35",
    views: 1_750_000,
    createdAt: new Date(now - 10 * day).toISOString(),
    channelId: "ch-3",
    categoryId: "technology",
    tags: ["microservices", "architecture", "backend", "system-design"],
    likes: 56_000,
    commentsCount: 2_100,
  },
]

export const comments: Comment[] = [
  {
    id: "cmt-1",
    content:
      "This is exactly what I needed. The explanation of server components finally clicked for me. Thanks!",
    userId: "u-1",
    videoId: "vid-1",
    likes: 1_200,
    repliesCount: 24,
    createdAt: new Date(now - 1 * day).toISOString(),
    user: {
      name: "Sarah Ahmed",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=sarah",
    },
  },
  {
    id: "cmt-2",
    content:
      "Great tutorial but I think you missed the part about error boundaries in server components. Could you do a follow-up?",
    userId: "u-2",
    videoId: "vid-1",
    likes: 340,
    repliesCount: 8,
    createdAt: new Date(now - 2 * day).toISOString(),
    user: {
      name: "Mike Chen",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=mike",
    },
  },
  {
    id: "cmt-3",
    content:
      "Color theory has always been a weakness of mine. This video made it so much clearer. Bookmarked!",
    userId: "u-3",
    videoId: "vid-2",
    likes: 890,
    repliesCount: 12,
    createdAt: new Date(now - 3 * day).toISOString(),
    user: {
      name: "Emily Park",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=emily",
    },
  },
  {
    id: "cmt-4",
    content: "The extension for git blame alone was worth watching the whole video.",
    userId: "u-4",
    videoId: "vid-3",
    likes: 2_100,
    repliesCount: 45,
    createdAt: new Date(now - 12 * day).toISOString(),
    user: {
      name: "Alex Rivera",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=alex",
    },
  },
  {
    id: "cmt-5",
    content: "I found the hidden dragon boss on my first playthrough but missed the rest 😅",
    userId: "u-5",
    videoId: "vid-4",
    likes: 4_500,
    repliesCount: 67,
    createdAt: new Date(now - 8 * day).toISOString(),
    user: {
      name: "Jordan Lee",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=jordan",
    },
  },
  {
    id: "cmt-6",
    content:
      "RSC is the future but the learning curve is real. Thanks for breaking it down so well.",
    userId: "u-6",
    videoId: "vid-5",
    likes: 560,
    repliesCount: 15,
    createdAt: new Date(now - 2 * day).toISOString(),
    user: {
      name: "Priya Sharma",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=priya",
    },
  },
  {
    id: "cmt-7",
    content: "7 days for a design system? That's impressive. Would love to see the Figma file.",
    userId: "u-7",
    videoId: "vid-6",
    likes: 780,
    repliesCount: 22,
    createdAt: new Date(now - 4 * day).toISOString(),
    user: {
      name: "Tom Wilson",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=tom",
    },
  },
  {
    id: "cmt-8",
    content: "TypeScript keeps getting better. The const type parameters are a game changer!",
    userId: "u-8",
    videoId: "vid-7",
    likes: 430,
    repliesCount: 9,
    createdAt: new Date(now - 1 * day).toISOString(),
    user: {
      name: "Nina Kosaka",
      avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=nina",
    },
  },
]
